name: gds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
          pip install cocotb

      - name: Install PDK
        run: |
          pip install volare
          volare ls-remote --pdk sky130
          volare enable --pdk sky130 --version fa87f8f4bbcc7255b6f0c0fb506960f531ae2392
          volare ls
          mkdir -p dependencies
          cp -r "$(volare --pdk sky130 --version fa87f8f4bbcc7255b6f0c0fb506960f531ae2392 path)" dependencies/sky130

      - name: Run GL test
        run: make GATES=yes -C test
        env:
          GATES: "yes"
          PDK_TYPE: "sky130"
          COCOTB_RESOLVE_X: "ZEROS"

      - name: Create dummy results.xml (on failure)
        if: failure()
        run: |
          mkdir -p test
          echo "<testsuite></testsuite>" > test/results.xml

      - name: Upload test summary
        uses: test-summary/action@v2.3
        with:
          paths: test/results.xml

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Viewer
        uses: TinyTapeout/tt-gds-action/viewer@ttsky25a
        with:
          pdk: sky130
