name: GDS Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            python3-pip \
            klayout \
            magic \
            git \
            wget \
            curl \
            make

      - name: Install PDK (Sky130)
        run: |
          pip install volare
          # Show available remote versions
          volare ls-remote --pdk sky130
          # Enable specific version (replace with "latest" if needed)
          volare enable --pdk sky130 fa87f8f4bbcc7255b6f0c0fb506960f531ae2392
          # List installed versions
          volare ls
          # Copy into dependencies (FIXED: no '..')
          mkdir -p dependencies
          cp -r "$(volare paths sky130 fa87f8f4bbcc7255b6f0c0fb506960f531ae2392)" dependencies/

      - name: Run Checks (DRC/LVS/etc.)
        run: |
          echo "Running DRC, LVS, and other checks..."
          # TODO: Replace this with your actual flow command, e.g.:
          # make gds
