name: gds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install PDK
        run: |
          pip install volare
          volare install --pdk sky130 --version latest
          volare enable --pdk sky130 --version latest
          volare list
          mkdir -p dependencies
          cp -r $(volare paths sky130 latest)/.. dependencies/

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies & PDK
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
          pip install cocotb volare
          volare install --pdk sky130 --version latest
          volare enable --pdk sky130 --version latest
          volare list

      - name: Run GL test
        run: make GATES=yes -C test
        env:
          GATES: "yes"
          PDK_TYPE: "sky130"
          COCOTB_RESOLVE_X: "ZEROS"

      - name: Create dummy results.xml (on failure)
        if: failure()
        run: |
          mkdir -p test
          echo "<testsuite></testsuite>" > test/results.xml

      - name: Upload test summary
        uses: test-summary/action@v2.3
        with:
          paths: test/results.xml

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Viewer
        uses: TinyTapeout/tt-gds-action/viewer@ttsky25a
        with:
          pdk: sky130
