name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: pip install -r test/requirements.txt

      - name: Run tests
        working-directory: test
        run: |
          make clean
          make
          # Check if the test failed by searching the results.xml for failure
          if grep -q "<failure" results.xml; then
            echo "Test failures detected!"
            exit 1
          fi

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: Upload VCD and results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test/tb.vcd
            test/results.xml
